codecov:
  require_ci_to_pass: yes
  branch: main

coverage:
  precision: 2
  round: down
  range:
    - 70
    - 100
  status:
    project: true
    patch: true
    changes: true

ignore:
  - "test"
  - "build"
  - ".dart_tool"
  - ".flutter-plugins-dependencies"
  - ".metadata"
  - "pubspec.lock"

comment:
  layout: "reach, diff, flags, tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
