const Map<String, String> microsoftRestoreCatalog = <String, String>{
  'Microsoft.WindowsStore': 'Microsoft Store',
  'Microsoft.StickyNotes': 'Sticky Notes',
  'Microsoft.WindowsAlarms': 'Clock',
  'Microsoft.WindowsFeedbackHub': 'Feedback Hub',
  'Microsoft.Todos': 'Microsoft To Do',
  'Microsoft.YourPhone': 'Phone Link',
  'Microsoft.OneDrive': 'OneDrive',
  'Microsoft.GamingApp': 'Xbox App',
  'Microsoft.XboxGamingOverlay': 'Xbox Game Bar',
  'Microsoft.XboxIdentityProvider': 'Xbox Identity Provider',
  'Clipchamp.Clipchamp': 'Clipchamp',
  'Microsoft.Family': 'Microsoft Family',
  'Microsoft.QuickAssist': 'Quick Assist',
  'Microsoft.PowerAutomateDesktop': 'Power Automate',
  'Microsoft.DevHome': 'Dev Home',
  'Microsoft.MicrosoftOfficeHub': 'Office Hub',
  'Microsoft.OutlookForWindows': 'Outlook (new)',
};
