import 'action_tweaks.dart';
import 'system_tweak.dart';

List<SystemTweak> createProgramToolTweaks() {
  return <SystemTweak>[
    // Core launcher actions (non-executable resources)
    BatchScriptTweak(
      id: 'tool_winscript_batch',
      title: 'WinScript Batch Utility',
      description: 'Runs bundled WinScript maintenance batch actions.',
      category: 'Drivers & Installers',
      batchSegments: <String>['winscript.bat'],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
    RegistryImportTweak(
      id: 'tool_import_minimal_services_profile',
      title: 'Import Minimal Services Profile',
      description:
          'Imports minimal service startup policy from bundled .reg file by Sapphire.',
      category: 'Drivers & Installers',
      registrySegments: <String>['minimal_services.reg'],
      actionLabel: 'Import',
      isAggressive: true,
    ),
    RegistryImportTweak(
      id: 'tool_import_disable_advanced_services_profile',
      title: 'Import Disable Advanced Services Profile',
      description:
          'Imports advanced services hard-disable profile from bundled .reg file by Sapphire.',
      category: 'Drivers & Installers',
      registrySegments: <String>['disable_advanced_services.reg'],
      actionLabel: 'Import',
      isAggressive: true,
    ),
    PowerShellCommandTweak(
      id: 'tool_fortnite_diagnostic_ping',
      title: 'Fortnite Diagnostic Ping Tool by Alexanderthedad',
      description:
          'Runs the official remote diagnostic command for Fortnite ping troubleshooting.',
      category: 'Drivers & Installers',
      command: 'irm https://alexanderthedad.com/ping-fortnite.ps1 | iex',
      actionLabel: 'Run Tool',
      isAggressive: true,
      warningMessage:
          'This action executes a remote PowerShell command from '
          'alexanderthedad.com. Continue only if you trust the source.',
    ),
    ExternalUrlLauncherTweak(
      id: 'tool_winslopr_releases',
      title: 'Download Winslopr',
      description:
          'Opens the official Winslopr releases page on GitHub in your browser.',
      category: 'Drivers & Installers',
      url: 'https://github.com/builtbybel/Winslopr/releases',
      actionLabel: 'Open Releases',
    ),
    PowerShellTerminalCommandTweak(
      id: 'tool_usb_latency_analyzer_v2_marius_heier',
      title: 'USB Latency Analyzer V2 by marius heier',
      description:
          'Runs Marius Heier\'s diagnostic tool in a visible elevated PowerShell window. This does not apply tweaks and is intended for console diagnostics output.',
      category: 'Drivers & Installers',
      command: 'irm https://tools.mariusheier.com/cpudirect.ps1 | iex',
      actionLabel: 'Run Tool',
      warningMessage:
          'This action executes a remote PowerShell command from tools.mariusheier.com. Continue only if you trust the source.',
    ),
    PowerShellTerminalCommandTweak(
      id: 'tool_install_win11_debloat_raphire',
      title: 'Install Win11 Debloat',
      description:
          'Runs the official Win11Debloat remote command in a visible elevated PowerShell window.',
      category: 'Drivers & Installers',
      command: '& ([scriptblock]::Create((irm "https://debloat.raphi.re/")))',
      actionLabel: 'Install',
      isAggressive: true,
      warningMessage:
          'This action executes a remote PowerShell command from debloat.raphi.re and can change system configuration. Continue only if you trust the source.',
    ),
    PowerShellTerminalCommandTweak(
      id: 'tool_sysinternals_suite_winget',
      title: 'Install Sysinternals Suite',
      description:
          'Installs Microsoft Sysinternals Suite with Winget. The PowerShell window stays open so you can read the final PATH/tool output.',
      category: 'Drivers & Installers',
      command: 'winget install -e --id Microsoft.Sysinternals.Suite',
      actionLabel: 'Install',
      isAggressive: true,
    ),
    PowerShellCommandTweak(
      id: 'tool_winsux_debloat',
      title: 'WinSux by Fr33hty',
      description:
          'Runs Fr33hty\'s remote WinSux debloat command. Invasive action with no in-app revert.',
      category: 'Privacy & Bloatware',
      command:
          'iwr https://github.com/FR33THYFR33THY/WinSux/raw/refs/heads/main/WinSux.ps1 -useb | iex',
      actionLabel: 'Run WinSux',
      isAggressive: true,
      warningMessage:
          'This action executes a remote PowerShell command from '
          'github.com/FR33THYFR33THY and applies invasive debloat changes. '
          'There is no in-app revert for this action. Continue only if you '
          'fully trust the source.',
    ),

    // Existing bundled tools
    ExecutableLauncherTweak(
      id: 'tool_unpark_cpu',
      title: 'Unpark CPU',
      description: 'CPU core unparking utility.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'UnparkCpu.exe'],
      actionLabel: 'Open',
    ),
    ExecutableLauncherTweak(
      id: 'tool_mouse_flat_curve',
      title: 'Mouse Flat Curve',
      description: 'Applies flat mouse acceleration curve settings.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'MouseFlatCurve.exe'],
      actionLabel: 'Open',
    ),
    ExecutableLauncherTweak(
      id: 'tool_mouse_movement_recorder',
      title: 'Mouse Movement Recorder',
      description: 'Checks effective mouse polling behavior.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'mousemovementrecorder.exe'],
      actionLabel: 'Open',
    ),
    ExecutableLauncherTweak(
      id: 'tool_controller_polling',
      title: 'Polling Tool',
      description: 'Controller polling rate measurement tool.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'polling.exe'],
      actionLabel: 'Open',
    ),
    ExecutableLauncherTweak(
      id: 'tool_queue_size_tuner',
      title: 'Queue Size Tuner',
      description: 'Storage queue tuning utility.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'QueueSize_Tuner.exe'],
      actionLabel: 'Open',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_power_settings_explorer',
      title: 'PowerSettingsExplorer',
      description: 'Advanced Windows power-plan settings editor.',
      category: 'Drivers & Installers',
      executableSegments: <String>[
        'programmi',
        'PowerSettingsExplorer',
        'PowerSettingsExplorer.exe',
      ],
      actionLabel: 'Open',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_interrupt_affinity_policy',
      title: 'Interrupt Affinity Policy Tool',
      description: 'Interrupt affinity and IRQ policy tuning utility.',
      category: 'Drivers & Installers',
      executableSegments: <String>[
        'programmi',
        'Interrupt_Affinity_Policy_Tool',
        'intPolicy_x64.exe',
      ],
      actionLabel: 'Open',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_interrupt_affinity_policy_x86',
      title: 'Interrupt Affinity Policy Tool (x86)',
      description: 'x86 build of interrupt affinity policy utility.',
      category: 'Drivers & Installers',
      executableSegments: <String>[
        'programmi',
        'Interrupt_Affinity_Policy_Tool',
        'intPolicy_x86.exe',
      ],
      actionLabel: 'Open',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_interrupt_affinity_policy_ia64',
      title: 'Interrupt Affinity Policy Tool (IA64)',
      description: 'IA64 build of interrupt affinity policy utility.',
      category: 'Drivers & Installers',
      executableSegments: <String>[
        'programmi',
        'Interrupt_Affinity_Policy_Tool',
        'intPolicy_ia64.exe',
      ],
      actionLabel: 'Open',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_gpuz',
      title: 'GPU-Z',
      description: 'Detailed GPU diagnostics and sensors.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'GPU-Z.2.69.0.exe'],
      actionLabel: 'Open',
    ),
    ExecutableLauncherTweak(
      id: 'tool_furmark_setup',
      title: 'FurMark Installer',
      description: 'GPU stress-test installer package.',
      category: 'Drivers & Installers',
      executableSegments: <String>[
        'programmi',
        'FurMark_2.10.2_Win64_Setup.exe',
      ],
      actionLabel: 'Install',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_more_clock_tool',
      title: 'More Clock Tool',
      description: 'AMD clock/voltage control utility.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'MoreClockTool.exe'],
      actionLabel: 'Open',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_more_power_tool_setup',
      title: 'MorePowerTool Installer',
      description: 'AMD power table tuning installer.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'MorePowerTool_Setup.exe'],
      actionLabel: 'Install',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_msi_afterburner_setup',
      title: 'MSI Afterburner Installer',
      description: 'GPU overclocking and monitoring installer.',
      category: 'Drivers & Installers',
      executableSegments: <String>[
        'programmi',
        'MSIAfterburnerSetup467Beta2.exe',
      ],
      actionLabel: 'Install',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_autoruns_folder',
      title: 'Autoruns',
      description: 'Startup and scheduled task analyzer suite.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'Autoruns'],
      launchExecutableRelativePath: 'Autoruns64.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_cpuz_folder',
      title: 'CPU-Z',
      description: 'CPU and memory information utility.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'cpu-z_2.19-en'],
      launchExecutableRelativePath: 'cpuz_x64.exe',
      actionLabel: 'Open',
    ),
    DirectoryLauncherTweak(
      id: 'tool_cru_folder',
      title: 'CRU',
      description: 'Custom Resolution Utility for display modes.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'cru-1.5.3'],
      launchExecutableRelativePath: 'CRU.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_hidusbf_folder',
      title: 'hidusbf',
      description: 'USB polling overclock toolkit for HID devices.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'hidusbf (BB11.5.25)'],
      launchExecutableRelativePath: 'DRIVER/Setup.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_hwinfo_folder',
      title: 'HWiNFO',
      description: 'System sensors and hardware telemetry suite.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'hwi_834'],
      launchExecutableRelativePath: 'HWiNFO64.EXE',
      actionLabel: 'Open',
    ),
    DirectoryLauncherTweak(
      id: 'tool_nvidia_profile_inspector_folder',
      title: 'NVIDIA Profile Inspector',
      description: 'Advanced NVIDIA profile editor.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'nvidiaProfileInspector'],
      launchExecutableRelativePath: 'nvidiaProfileInspector.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    ExplorerSelectFileTweak(
      id: 'tool_nvidia_profile_inspector_nip_profile',
      title: 'NVIDIA Performance Settings (.nip)',
      description:
          'Performance-focused profile. Do not use if you are looking for visual quality.',
      category: 'Drivers & Installers',
      fileSegments: <String>['nvidia-performance-settings.nip'],
      actionLabel: 'Show in Explorer',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_prime95_folder',
      title: 'Prime95',
      description: 'CPU stress-test and stability validation.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'p95v3019b20.win64'],
      launchExecutableRelativePath: 'prime95.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_testmem5_folder',
      title: 'TestMem5',
      description: 'RAM stress-test utility.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'TestMem5'],
      launchExecutableRelativePath: 'TM5.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),

    // Newly integrated external and bundled utilities
    DirectoryLauncherTweak(
      id: 'tool_rammap_folder',
      title: 'RAMMap',
      description: 'Microsoft Sysinternals physical memory analysis utility.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'RAMMap'],
      launchExecutableRelativePath: 'RAMMap64.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_device_cleanup_folder',
      title: 'Device Cleanup',
      description: 'Cleans phantom/non-present device entries from Windows.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'DeviceCleanup'],
      launchExecutableRelativePath: 'DeviceCleanup.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_driver_store_explorer_folder',
      title: 'Driver Store Explorer (RAPR)',
      description: 'Inspects and prunes old/unused driver packages.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'DriverStoreExplorer-v1.0.26'],
      launchExecutableRelativePath: 'Rapr.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_dismpp_folder',
      title: 'Dism++',
      description: 'Advanced DISM and servicing operations toolkit.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'Dism++10.1.1002.1B'],
      launchExecutableRelativePath: 'Dism++x64.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_cleanmgrplus_folder',
      title: 'Cleanmgr+',
      description:
          'Extended disk cleanup and temporary-file management utility.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'cleanmgrplus'],
      launchExecutableRelativePath: 'Cleanmgr+.exe',
      actionLabel: 'Open',
    ),
    ExecutableLauncherTweak(
      id: 'tool_gpu_dword_manager',
      title: 'GPU DWORD Manager',
      description: 'GPU registry DWORD tuning utility.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'GPU_Dword_Manager.exe'],
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_msi_util_folder',
      title: 'MSI Utility v3',
      description: 'Message Signaled Interrupt policy utility.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'MSI_util_v3'],
      launchExecutableRelativePath: 'MSI_util_v3.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    ExecutableLauncherTweak(
      id: 'tool_polling_rate_tester_app',
      title: 'Polling Rate Tester App',
      description: 'Dedicated mouse polling rate validation utility.',
      category: 'Drivers & Installers',
      executableSegments: <String>[
        'programmi',
        'PollingRateTesterApp_v1.00.01.exe',
      ],
      actionLabel: 'Open',
    ),
    DirectoryLauncherTweak(
      id: 'tool_radeon_tuner_folder',
      title: 'Radeon Tuner',
      description: 'AMD Radeon driver tuning and profile utility.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'RadeonTuner'],
      launchExecutableRelativePath: 'RadeonTuner.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_tcp_optimizer_folder',
      title: 'TCP Optimizer',
      description: 'Network stack optimization and diagnostics tool.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'TCPOptimizer'],
      launchExecutableRelativePath: 'TCPOptimizer.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_vivetool_folder',
      title: 'ViVeTool',
      description: 'Windows feature flag management utility.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'ViVeTool-v0.3.4-IntelAmd'],
      launchExecutableRelativePath: 'ViVeTool.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_star_ethernet_analyzer_folder',
      title: 'Star Ethernet Analyzer',
      description: 'Ethernet and jitter diagnostics toolkit.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'Star Ethernet Analyzer'],
      launchExecutableRelativePath: '2. StarTrinity.Installer.exe',
      actionLabel: 'Open',
    ),
    ScriptInteractiveTweak(
      id: 'tool_star_ethernet_analyzer_script',
      title: 'Star Ethernet Analyzer Script',
      description: 'Interactive helper script for Star Ethernet Analyzer.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'programmi',
        'Star Ethernet Analyzer',
        'StarAnalyzer_bam.ps1',
      ],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
    BatchScriptTweak(
      id: 'tool_star_ethernet_analyzer_start_bat',
      title: 'Star Ethernet Analyzer Launcher',
      description:
          'Runs the bundled batch launcher for Star Ethernet Analyzer.',
      category: 'Drivers & Installers',
      batchSegments: <String>[
        'programmi',
        'Star Ethernet Analyzer',
        '3. Start Analyzer here.bat',
      ],
      actionLabel: 'Run Script',
    ),

    // User-provided external tools (graceful if absent)
    DirectoryLauncherTweak(
      id: 'tool_process_explorer_folder',
      title: 'Process Explorer',
      description: 'Microsoft Sysinternals advanced process inspector.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'ProcessExplorer'],
      launchExecutableRelativePath: 'procexp64.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_process_monitor_folder',
      title: 'Process Monitor',
      description: 'Microsoft Sysinternals realtime system activity monitor.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'ProcessMonitor'],
      launchExecutableRelativePath: 'procmon64.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_tcpview_folder',
      title: 'TCPView',
      description: 'Microsoft Sysinternals TCP/UDP endpoint monitor.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'TCPView'],
      launchExecutableRelativePath: 'tcpview64.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),
    DirectoryLauncherTweak(
      id: 'tool_latencymon_folder',
      title: 'LatencyMon',
      description: 'Realtime DPC/ISR latency analysis utility.',
      category: 'Drivers & Installers',
      directorySegments: <String>['programmi', 'LatencyMon'],
      launchExecutableRelativePath: 'latencymon.exe',
      actionLabel: 'Open',
      isAggressive: true,
    ),

    // Newly added scripts and programs
    ExecutableLauncherTweak(
      id: 'tool_rtl_utility',
      title: 'RTL Utility',
      description: 'Realtek utility and diagnostics tool.',
      category: 'Drivers & Installers',
      executableSegments: <String>['programmi', 'RTL_Utility_1_0_12_x64.exe'],
      actionLabel: 'Open',
      isAggressive: true,
    ),
    BatchScriptTweak(
      id: 'tool_fix_tools_runner',
      title: 'Fix Tools Launcher',
      description: 'Runs the Fix Tools batch launcher menu.',
      category: 'Drivers & Installers',
      batchSegments: <String>['interactive_scripts', 'Fix Tools', 'run.bat'],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
    ScriptInteractiveTweak(
      id: 'tool_fix_tools_battery_report',
      title: 'Battery Report',
      description: 'Fix Tools diagnostic script.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'interactive_scripts',
        'Fix Tools',
        'BatteryReport.ps1',
      ],
      actionLabel: 'Run Script',
    ),
    ScriptInteractiveTweak(
      id: 'tool_fix_tools_change_name',
      title: 'Change Name',
      description: 'Fix Tools helper script.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'interactive_scripts',
        'Fix Tools',
        'Change Name.ps1',
      ],
      actionLabel: 'Run Script',
    ),
    ScriptInteractiveTweak(
      id: 'tool_fix_tools_fastclean',
      title: 'FastClean',
      description: 'Fix Tools cleanup script.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'interactive_scripts',
        'Fix Tools',
        'FastClean.ps1',
      ],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
    ScriptInteractiveTweak(
      id: 'tool_fix_tools_permessi',
      title: 'Permessi',
      description: 'Fix Tools permissions repair script.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'interactive_scripts',
        'Fix Tools',
        'Permessi.ps1',
      ],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
    ScriptInteractiveTweak(
      id: 'tool_fix_tools_reset_network',
      title: 'Reset Network',
      description: 'Fix Tools network reset script.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'interactive_scripts',
        'Fix Tools',
        'ResetNetwork.ps1',
      ],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
    ScriptInteractiveTweak(
      id: 'tool_fix_tools_ripristina_anteprime',
      title: 'Ripristina Anteprime',
      description: 'Fix Tools thumbnail cache repair script.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'interactive_scripts',
        'Fix Tools',
        'RipristinaAntemprime.ps1',
      ],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
    ScriptInteractiveTweak(
      id: 'tool_fix_tools_sfc_dism',
      title: 'SFC & DISM',
      description: 'Fix Tools integrity and image repair script.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'interactive_scripts',
        'Fix Tools',
        'SFC & DISM.ps1',
      ],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
    ScriptInteractiveTweak(
      id: 'tool_gaming_net_diagnostic',
      title: 'Gaming Network Diagnostic',
      description: 'Quick network diagnostics script for gaming sessions.',
      category: 'Drivers & Installers',
      scriptSegments: <String>[
        'interactive_scripts',
        'gaming_net_diagnostic.ps1',
      ],
      actionLabel: 'Run Script',
      isAggressive: true,
    ),
  ];
}
