import 'action_tweaks.dart';
import 'system_tweak.dart';

// Format: [!]<id>|<title>|<source category>|<resource path>.
// A leading ! marks actions that require the aggressive safety gate.
const List<String> _scriptDefinitions = <String>[
  '!setup_memory_compression_script|Memory Compression (Script Variant)|Setup Scripts|interactive_scripts/3 Setup/2 Memory Compression.ps1',
  '!setup_activation_script|Activation (Script Variant)|Setup Scripts|interactive_scripts/3 Setup/5 Activation.ps1',
  '!setup_background_apps_script|Background Apps (Script Variant)|Setup Scripts|interactive_scripts/3 Setup/9 Background Apps.ps1',
  'setup_edge_settings_script|Edge Settings (Script Variant)|Setup Scripts|interactive_scripts/3 Setup/10 Edge Settings.ps1',
  'setup_store_settings_script|Store Settings (Script Variant)|Setup Scripts|interactive_scripts/3 Setup/11 Store Settings.ps1',
  '!refresh_factory_reset|Factory Reset|Refresh & Recovery|interactive_scripts/2 Refresh/1 Factory Reset.ps1',
  '!refresh_account_local|Account Local|Refresh & Recovery|interactive_scripts/2 Refresh/2 Account Local.ps1',
  '!refresh_reinstall|Reinstall|Refresh & Recovery|interactive_scripts/2 Refresh/3 Reinstall.ps1',
  '!refresh_autounattend|Autounattend|Refresh & Recovery|interactive_scripts/2 Refresh/4 Autounattend.ps1',
  '!refresh_updates_drivers_block|Updates Drivers Block|Refresh & Recovery|interactive_scripts/2 Refresh/5 Updates Drivers Block.ps1',
  '!refresh_network_driver|Network Driver|Refresh & Recovery|interactive_scripts/1 Check/4 Bios Update.ps1',
  '!refresh_to_bios|To BIOS|Refresh & Recovery|interactive_scripts/2 Refresh/7 To Bios.ps1',
  '!setup_bitlocker|BitLocker|Setup Scripts|interactive_scripts/3 Setup/1 BitLocker.ps1',
  '!setup_convert_home_to_pro|Convert Home To Pro|Setup Scripts|interactive_scripts/3 Setup/3 Convert Home To Pro.ps1',
  '!setup_keys|Keys|Setup Scripts|interactive_scripts/3 Setup/4 Keys.ps1',
  'setup_date_language_region_time|Date Language Region Time|Setup Scripts|interactive_scripts/3 Setup/6 Date Language Region Time.ps1',
  'setup_startup_apps_7|Startup Apps (7)|Setup Scripts|interactive_scripts/3 Setup/7 Startup Apps.ps1',
  'setup_startup_apps_8|Startup Apps (8)|Setup Scripts|interactive_scripts/3 Setup/8 Startup Apps.ps1',
  '!setup_updates_pause|Updates Pause|Setup Scripts|interactive_scripts/3 Setup/12 Updates Pause.ps1',
  'installers_menu|Installers Menu|Drivers & Installers|interactive_scripts/4 Installers/1 Installers.ps1',
  '!installers_msi_afterburner|MSI Afterburner Script Installer|Drivers & Installers|interactive_scripts/4 Installers/2 MSI Afterburner.ps1',
  '!installers_nvidia_profile_inspector|NVIDIA Profile Inspector Script Installer|Drivers & Installers|interactive_scripts/4 Installers/3 Nvidia Profile Inspector.ps1',
  '!installers_more_clock_tool|More Clock Tool Script Installer|Drivers & Installers|interactive_scripts/4 Installers/4 More Clock Tool.ps1',
  '!installers_cru_sre|CRU SRE Script Installer|Drivers & Installers|interactive_scripts/4 Installers/5 CRU SRE.ps1',
  '!graphics_driver_clean|Driver Clean|Graphics Scripts|interactive_scripts/5 Graphics/1 Driver Clean.ps1',
  '!graphics_driver_install_latest|Driver Install Latest|Graphics Scripts|interactive_scripts/5 Graphics/2 Driver Install Latest.ps1',
  '!graphics_driver_install_debloat_settings|Driver Install Debloat & Settings|Graphics Scripts|interactive_scripts/5 Graphics/3 Driver Install Debloat & Settings.ps1',
  '!graphics_nvidia_settings|NVIDIA Settings|Graphics Scripts|interactive_scripts/5 Graphics/4 Nvidia Settings.ps1',
  '!graphics_amd_settings|AMD Settings|Graphics Scripts|interactive_scripts/5 Graphics/5 Amd Settings.ps1',
  '!graphics_intel_settings|Intel Settings|Graphics Scripts|interactive_scripts/5 Graphics/6 Intel Settings.ps1',
  '!graphics_hdcp|HDCP|Graphics Scripts|interactive_scripts/5 Graphics/7 Hdcp.ps1',
  '!graphics_p0_state|P0 State|Graphics Scripts|interactive_scripts/5 Graphics/8 P0 State.ps1',
  '!graphics_msi_mode_script|MSI Mode (Script Variant)|Graphics Scripts|interactive_scripts/5 Graphics/9 Msi Mode.ps1',
  '!graphics_directx|DirectX Runtime|Graphics Scripts|interactive_scripts/5 Graphics/10 DirectX.ps1',
  '!graphics_cpp_runtime|C++ Runtime|Graphics Scripts|interactive_scripts/5 Graphics/11 C++.ps1',
  'graphics_resolution_refresh_rate|Resolution Refresh Rate|Graphics Scripts|interactive_scripts/5 Graphics/12 Resolution Refresh Rate.ps1',
  '!graphics_hags_windowed|HAGS Windowed|Graphics Scripts|interactive_scripts/5 Graphics/13 Hags Windowed.ps1',
  '!windows_start_menu_taskbar_script|Start Menu Taskbar (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/1 Start Menu Taskbar.ps1',
  '!windows_start_menu_layout_script|Start Menu Layout (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/2 Start Menu Layout.ps1',
  '!windows_start_menu_shortcuts_script|Start Menu Shortcuts (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/3 Start Menu Shortcuts.ps1',
  '!windows_context_menu_script|Context Menu (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/4 Context Menu.ps1',
  '!windows_theme_black_script|Theme Black (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/5 Theme Black.ps1',
  'windows_signout_lockscreen_wallpaper_black|Signout Lockscreen Wallpaper Black|Windows Scripts|interactive_scripts/6 Windows/6 Signout Lockscreen Wallpaper Black.ps1',
  'windows_user_account_pictures_black|User Account Pictures Black|Windows Scripts|interactive_scripts/6 Windows/7 User Account Pictures Black.ps1',
  '!windows_widgets_script|Widgets (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/8 Widgets.ps1',
  '!windows_copilot_script|Copilot (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/9 Copilot.ps1',
  'windows_gamemode|Gamemode|Windows Scripts|interactive_scripts/6 Windows/10 Gamemode.ps1',
  '!windows_pointer_precision_script|Pointer Precision (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/11 Pointer Precision.ps1',
  'windows_scaling|Scaling|Windows Scripts|interactive_scripts/6 Windows/12 Scaling.ps1',
  'windows_notepad_settings|Notepad Settings|Windows Scripts|interactive_scripts/6 Windows/13 Notepad Settings.ps1',
  '!windows_control_panel_settings_script|Control Panel Settings (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/14 Control Panel Settings.ps1',
  'windows_sound|Sound|Windows Scripts|interactive_scripts/6 Windows/15 Sound.ps1',
  '!windows_loudness_eq|Loudness EQ|Windows Scripts|interactive_scripts/6 Windows/16 Loudness EQ.ps1',
  '!windows_device_manager_power_savings_wake|Device Manager Power Savings & Wake|Windows Scripts|interactive_scripts/6 Windows/17 Device Manager Power Savings & Wake.ps1',
  '!windows_nvme_faster_driver|NVME Faster Driver|Windows Scripts|interactive_scripts/6 Windows/20 NVME Faster Driver.ps1',
  '!windows_write_cache_buffer_flushing|Write Cache Buffer Flushing|Windows Scripts|interactive_scripts/6 Windows/21 Write Cache Buffer Flushing.ps1',
  '!windows_network_adapter_power_savings_script|Network Adapter Power Savings & Wake (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/18 Network Adapter Power Savings & Wake.ps1',
  '!windows_network_ipv4_only_script|Network IPv4 Only (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/19 Network IPv4 Only.ps1',
  '!windows_gamebar_script|Gamebar (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/22 Gamebar.ps1',
  '!windows_edge_webview_script|Edge & WebView (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/23 Edge & WebView.ps1',
  '!windows_bloatware_script|Bloatware (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/24 Bloatware.ps1',
  '!windows_bloatware_legacy_apps_check_script|Bloatware Legacy Apps Check (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/25 Bloatware Legacy Apps Check.ps1',
  '!windows_bloatware_legacy_features_check_script|Bloatware Legacy Features Check (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/26 Bloatware Legacy Features Check.ps1',
  '!windows_bloatware_uwp_apps_check_script|Bloatware UWP Apps Check (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/27 Bloatware UWP Apps Check.ps1',
  '!windows_bloatware_uwp_features_check_script|Bloatware UWP Features Check (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/28 Bloatware UWP Features Check.ps1',
  '!windows_bloatware_taskmgr_check_script|Bloatware TaskMgr Check (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/29 Bloatware TaskMgr Check.ps1',
  '!windows_power_plan_script|Power Plan (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/30 Power Plan.ps1',
  '!windows_timer_resolution_script|Timer Resolution (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/31 Timer Resolution.ps1',
  '!windows_uac_script|UAC (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/32 UAC.ps1',
  '!windows_core_isolation_script|Core Isolation (Script Variant)|Windows Scripts|interactive_scripts/6 Windows/33 Core Isolation.ps1',
  '!windows_defender_optimize|Defender Optimize|Windows Scripts|interactive_scripts/6 Windows/34 Defender Optimize.ps1',
  '!windows_autoruns_startup_tasks_apps_check|Autoruns Startup Tasks & Apps Check|Windows Scripts|interactive_scripts/6 Windows/35 Autoruns Startup Tasks & Apps Check.ps1',
  '!windows_cleanup|Cleanup|Windows Scripts|interactive_scripts/6 Windows/36 Cleanup.ps1',
  '!windows_restore_point|Restore Point|Windows Scripts|interactive_scripts/6 Windows/37 Restore Point.ps1',
  '!advanced_defender|Defender|Advanced Scripts|interactive_scripts/8 Advanced/1 Defender.ps1',
  '!advanced_firewall_script|Firewall (Script Variant)|Advanced Scripts|interactive_scripts/8 Advanced/2 Firewall.ps1',
  '!advanced_spectre_meltdown_script|Spectre Meltdown (Script Variant)|Advanced Scripts|interactive_scripts/8 Advanced/3 Spectre Meltdown.ps1',
  '!advanced_dep_script|Data Execution Prevention (Script Variant)|Advanced Scripts|interactive_scripts/8 Advanced/4 Data Execution Prevention.ps1',
  '!advanced_file_download_security_warning|File Download Security Warning|Advanced Scripts|interactive_scripts/8 Advanced/5 File Download Security Warning.ps1',
  '!advanced_mmagent_features_script|MMAgent Features (Script Variant)|Advanced Scripts|interactive_scripts/8 Advanced/6 MMAgent Features.ps1',
  '!advanced_rebar_force|ReBar Force|Advanced Scripts|interactive_scripts/8 Advanced/7 ReBar Force.ps1',
  '!advanced_smt_ht|SMT HT|Advanced Scripts|interactive_scripts/8 Advanced/8 Smt Ht.ps1',
  '!advanced_core_1_thread_1|Core 1 Thread 1|Advanced Scripts|interactive_scripts/8 Advanced/9 Core 1 Thread 1.ps1',
  '!advanced_priority|Priority|Advanced Scripts|interactive_scripts/8 Advanced/10 Priority.ps1',
  '!advanced_mpo_script|MPO (Script Variant)|Advanced Scripts|interactive_scripts/8 Advanced/11 Mpo.ps1',
  '!advanced_hardware_legacy_flip_script|Hardware Legacy Flip (Script Variant)|Advanced Scripts|interactive_scripts/8 Advanced/12 Hardware Legacy Flip.ps1',
  '!advanced_hardware_composed_flip_script|Hardware Composed Independent Flip (Script Variant)|Advanced Scripts|interactive_scripts/8 Advanced/13 Hardware Composed Independent Flip.ps1',
  '!advanced_ulps_script|ULPS (Script Variant)|Advanced Scripts|interactive_scripts/8 Advanced/14 Ulps.ps1',
  '!advanced_driver_whql_secure_boot_bypass|Driver WHQL Secure Boot Bypass|Advanced Scripts|interactive_scripts/8 Advanced/15 Driver Whql Secure Boot Bypass.ps1',
  '!advanced_keyboard_shortcuts|Keyboard Shortcuts|Advanced Scripts|interactive_scripts/8 Advanced/16 Keyboard Shortcuts.ps1',
  '!advanced_services|Services|Advanced Scripts|interactive_scripts/8 Advanced/17 Services.ps1',
  '!advanced_start_search_shell_mobsync|Start Search Shell Mobsync|Advanced Scripts|interactive_scripts/8 Advanced/18 Start Search Shell Mobsync.ps1',
];

List<SystemTweak> createRecoveredScriptTweaks() {
  return _scriptDefinitions
      .map((definition) {
        final fields = definition.split('|');
        if (fields.length != 4) {
          throw StateError('Invalid recovered script definition: $definition');
        }

        final aggressive = fields[0].startsWith('!');
        return ScriptInteractiveTweak(
          id: aggressive ? fields[0].substring(1) : fields[0],
          title: fields[1],
          description: 'Interactive script by Fr33thy.',
          category: fields[2],
          scriptSegments: fields[3].split('/'),
          isAggressive: aggressive,
        );
      })
      .toList(growable: false);
}
